### ISSUE TITLE
Homekit Auto Refresh of Blynk Data

### ISSUE THREAD

**Issue by kdubovenko** [ilcato/homebridge-blynk#13]
@blynkkk @ilcato @doom369 Hi All, first of all I've been experimenting with ESP8266 + Blynk + Homebridge, thank you for putting all of this together! The only issue that I am running into is that when I run homekit, the values of the temperature, humidity, etc are not refreshed unless I open / close the app or ask Siri for the status. In other words, I have to manually poll the homebridge server for data. Is there a way to set refresh rates for all of the sensors that would make Homekit perform like the Blynk app in terms of near real-time data updates? I would like to be able to set up automation routines through Homekit, which is currently impractical due to manual polling. Thanks!

**Comment by ilcato** [comment]
With the new version it should work. Pay attention to the new config format.
