### ISSUE TITLE
Bad pin triggered

### ISSUE THREAD

**Issue by meyer59** [ilcato/homebridge-blynk#18]
Hi,
When the accessorie's pin is triggered it is always the `D3` pin even if in the conf.json i set up another pin like `D0`, anyone is having this problem ?
Here is my conf.json:

{
    "bridge": {
        "name": "Homebridge",
        "username": "B8:27:EB:07:90:8P",
        "port": 51826,
        "pin": "090-**-268"
    },

    "description": "Descritpion",

    "platforms": [
            {
            "platform": "Blynk",
            "name": "Blynk",
            "serverurl": "http://192.168.**.**:8080",
            "pollerperiod": "0",
            "token" : "7*****************************e97",
            "dashboardName": "Blynk app",
            "accessories": [
                {
                    "name":             "Portail",
                    "widget":           "Switch",
                    "mode":             "PUSH",
                    "caption":          "Portail",
                    "pin":              "D0"
                }
            ]
        }
    ],
    "accessories":[
    ]

}
`
`

**Comment by ilcato** [comment]
What do you have in your project?

**Comment by meyer59** [comment]
Blynk project ?

**Comment by ilcato** [comment]
yes

**Comment by meyer59** [comment]
![image-1](https://user-images.githubusercontent.com/9505463/46619392-4a428480-cb22-11e8-84be-2da94210226f.jpg)

**Comment by meyer59** [comment]
![webp net-resizeimage](https://user-images.githubusercontent.com/9505463/46619508-8c6bc600-cb22-11e8-83e1-89c5ff048a8e.jpg)

The blynk app is working fine.

**Comment by ilcato** [comment]
So you are saying that in the Home app you have the Portal accessory and when you press it you are activating the D3 widget on the Blynk side?

**Comment by meyer59** [comment]
Yes. But it seems to be something with cache because at the begining i put the D3 pin for testing purpose, and since it is always the D3.
Maybe i will try to reinstall everything tonight and we'll see

**Comment by ilcato** [comment]
Try to delete the accessories folder and restart homebridge

**Comment by meyer59** [comment]
it worked, thank you!
