### ISSUE TITLE
Noob troubleshooting

### ISSUE THREAD

**Issue by eqsone** [ilcato/homebridge-blynk#6]
Hey ilcato, thanks for your work! 

I followed the setup-guides but can't seem to get Blynk to work with HomeKit, so I would like to ask for further advice:

In order to make it work, a local Blynk server should be set up. Check.
Local Blynk server is accessible through the Blynk App (iOS) and switches Buttons. Check.
'homebridge-blynk' plugin needs to be installed. Check.
Homebridges' config.json should be edited as advised. Check.
In iOS10 within 'Home-App' Homebridge (running on a Raspberry) is available and already switches Hue Lights with the dedicated hue-plugin installed. Check.

Now when I add the Blynk platform to Homebridges' config.json, 'Home-App' shows all my added Blynk-buttons but keeps searching for all the devices as if none of them would answer. Double checked the config.json for valid quotes.

I presume the Homebridge's IP will do for the Blynks' "server" entry?

Has the local Blynk server got to be ssl secured with own certificates in order to talk to HomeKit?

My Blynk server is installed on the same Raspberry that runs Homebridge, connected to my local network. I still use the provided build-in SSL certificates because when asking 'certbot' for own certificates, I have no clue what to put in for the 'YOUR_HOST' value and it doesn't accept plain IP-addresses:

./certbot-auto certonly --agree-tos --email YOUR_EMAIL --standalone -d YOUR_HOST

Do you see something obvious that I am still missing or doing entirely wrong here?

**Comment by ilcato** [comment]
Complete rewrite of the plugin. You should be have no problem now.
