### ISSUE TITLE
Switch accessory not working

### ISSUE THREAD

**Issue by mblackwell1002** [ilcato/homebridge-blynk#9]
My setup is as follows:
Rpi3 running a local Blynk server and homebridge
ESP8266-12E connecting to Blynk local server and providing data from DHT-11 and controlling 5 RF outlets via RF-TX chip (each RF outlet is actuated via a command from a virtual pin in the Blynk app)
iOS 10 iPhone with Blynk app and homeKit.

I have followed the steps for homebrige-blynk and am able to see all of the defined accessories from the config file.  The temperature and humidity readings are properly displayed in homeKit and on the Blynk app (although it appears that homebridge-blynk automatically converts the data to *F)

The problem i am having is with the 5 virtual switches.  While they do appear in my apple homeKit, I cannot control them from homeKit.  Also, the states do not update when the switches are toggled in the iOS Blynk app.

I have full control of all of my RF outlets through the Blynk app which is connected to the local Blynk server.

**Comment by ilcato** [comment]
Try now, I just completely rewritten the plugin. Pay attention to the new config.
